def zenkaku2hankaku(filename)
kanaHash = Hash.new{|hash,key| hash[key] = key}
kanaHash["ƒA"] = "±"
kanaHash["ƒC"] = "²"
kanaHash["ƒE"] = "³"
kanaHash["ƒG"] = "´"
kanaHash["ƒI"] = "µ"
kanaHash["ƒJ"] = "¶"
kanaHash["ƒL"] = "·"
kanaHash["ƒN"] = "¸"
kanaHash["ƒP"] = "¹"
kanaHash["ƒR"] = "º"
kanaHash["ƒT"] = "»"
kanaHash["ƒV"] = "¼"
kanaHash["ƒX"] = "½"
kanaHash["ƒZ"] = "¾"
kanaHash["ƒ\"] = "¿"
kanaHash["ƒ^"] = "À"
kanaHash["ƒ`"] = "Á"
kanaHash["ƒc"] = "Â"
kanaHash["ƒe"] = "Ã"
kanaHash["ƒg"] = "Ä"
kanaHash["ƒi"] = "Å"
kanaHash["ƒj"] = "Æ"
kanaHash["ƒk"] = "Ç"
kanaHash["ƒl"] = "È"
kanaHash["ƒm"] = "É"
kanaHash["ƒn"] = "Ê"
kanaHash["ƒq"] = "Ë"
kanaHash["ƒt"] = "Ì"
kanaHash["ƒw"] = "Í"
kanaHash["ƒz"] = "Î"
kanaHash["ƒ}"] = "Ï"
kanaHash["ƒ~"] = "Ğ"
kanaHash["ƒ€"] = "Ñ"
kanaHash["ƒ"] = "Ò"
kanaHash["ƒ‚"] = "Ó"
kanaHash["ƒ„"] = "Ô"
kanaHash["ƒ†"] = "Õ"
kanaHash["ƒˆ"] = "Ö"
kanaHash["ƒ‰"] = "×"
kanaHash["ƒŠ"] = "Ø"
kanaHash["ƒ‹"] = "Ù"
kanaHash["ƒŒ"] = "Ú"
kanaHash["ƒ"] = "Û"
kanaHash["ƒ"] = "Ü"
kanaHash["ƒ’"] = "¦"
kanaHash["ƒ“"] = "İ"
kanaHash["ƒ@"] = "§"
kanaHash["ƒB"] = "¨"
kanaHash["ƒD"] = "©"
kanaHash["ƒF"] = "ª"
kanaHash["ƒH"] = "«"
kanaHash["ƒb"] = "¯"
kanaHash["ƒƒ"] = "¬"
kanaHash["ƒ…"] = "­"
kanaHash["ƒ‡"] = "®"
kanaHash["ƒ”"] = "³Ş"
kanaHash["ƒK"] = "¶Ş"
kanaHash["ƒM"] = "·Ş"
kanaHash["ƒO"] = "¸Ş"
kanaHash["ƒQ"] = "¹Ş"
kanaHash["ƒS"] = "ºŞ"
kanaHash["ƒU"] = "»Ş"
kanaHash["ƒW"] = "¼Ş"
kanaHash["ƒY"] = "½Ş"
kanaHash["ƒ["] = "¾Ş"
kanaHash["ƒ]"] = "¿Ş"
kanaHash["ƒ_"] = "ÀŞ"
kanaHash["ƒa"] = "ÁŞ"
kanaHash["ƒd"] = "ÂŞ"
kanaHash["ƒf"] = "ÃŞ"
kanaHash["ƒh"] = "ÄŞ"
kanaHash["ƒo"] = "ÊŞ"
kanaHash["ƒr"] = "ËŞ"
kanaHash["ƒu"] = "ÌŞ"
kanaHash["ƒx"] = "ÍŞ"
kanaHash["ƒ{"] = "ÎŞ"
kanaHash["ƒp"] = "Êß"
kanaHash["ƒs"] = "Ëß"
kanaHash["ƒv"] = "Ìß"
kanaHash["ƒy"] = "Íß"
kanaHash["ƒ|"] = "Îß"
kanaHash["‚O"] = "0"
kanaHash["‚P"] = "1"
kanaHash["‚Q"] = "2"
kanaHash["‚R"] = "3"
kanaHash["‚S"] = "4"
kanaHash["‚T"] = "5"
kanaHash["‚U"] = "6"
kanaHash["‚V"] = "7"
kanaHash["‚W"] = "8"
kanaHash["‚X"] = "9"
kanaHash["I"] = "\!"
kanaHash["h"] = "\""
kanaHash["”"] = "\#"
kanaHash[""] = "\$"
kanaHash["“"] = "\%"
kanaHash["•"] = "\&"
kanaHash["f"] = "\'"
kanaHash["i"] = "\("
kanaHash["j"] = "\)"
kanaHash["O"] = "\^"
kanaHash["`"] = "\~"
kanaHash[""] = "\\"
kanaHash["b"] = "\|"
kanaHash["A"] = "\,"
kanaHash["C"] = "\,"
kanaHash["B"] = "\."
kanaHash["Q"] = "\_"
kanaHash["{"] = "\+"
kanaHash["|"] = "\-"
kanaHash["["] = "\-"
kanaHash["–"] = "\*"
kanaHash["^"] = "\/"
kanaHash["G"] = "\;"
kanaHash["F"] = "\:"
kanaHash["ƒ"] = "\<"
kanaHash["„"] = "\>"
kanaHash["u"] = "\["
kanaHash["v"] = "\]"
kanaHash["o"] = "\{"
kanaHash["p"] = "\}"
kanaHash["—"] = "\@"
kanaHash[""] = "\="
str = String.new
new_filename = filename + '_'
new_file = File.open(new_filename,"w")
File.open(filename){|io|
	while line = io.gets
		line  =~ /values.+\;/
		if $&.nil?
			new_file << line
		else
			chars = $&.split(//s)
			chars.each{|char|
				str += kanaHash[char]
			}
			new_line = $` + str
			new_file << new_line
			str = String.new
		end
	end
}
new_file.close
end

zenkaku2hankaku(ARGV[0])
